---
- name: Install packages
  block:
  - name: Create list of packages to be installed
    set_fact:
      package_list: "{{ package_list + cache_package_list }}"
    when: cache_enabled|bool

  - name: Install required packages
    yum:
      name: "{{ package_list }}"
      state: present
      update_cache: true
    become: yes
  tags: packages
