---
- name: Regather Network Facts
  setup:
    gather_subset:
      - network
  tags:
  - network_facts

- name: Set External Subnet with IPv4
  set_fact:
    extcidrnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv4.address }}/{{ansible_default_ipv4.netmask }}"
  when:
    - (extcidrnet is not defined or extcidrnet|length < 1)
    - not ipv6_enabled|bool or
      ipv4_baremetal|bool
  tags:
  - network_facts

- name: Set External Subnet with IPv6
  set_fact:
    extcidrnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_default_ipv6.address }}/64"
  when:
    - (extcidrnet is not defined or extcidrnet|length < 1)
    - ipv6_enabled|bool
    - not ipv4_baremetal|bool
  tags:
  - network_facts

- name: set provisioning subnet with IPV4
  set_fact:
    provisioning_subnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_facts[provisioning_bridge]['ipv4']['address'] }}/{{ ansible_facts[provisioning_bridge]['ipv4']['netmask'] }}"
  when: (not ipv6_enabled|bool) or
        ((release_version[0]|int == 4) and (release_version[2]|int == 3)) or
        (ipv4_provisioning|bool) or
        (not enable_redfish_virtualmedia|bool and not enable_idrac_virtualmedia|bool)
  tags:
  - network_facts

- name: set provisioning subnet with IPV6
  set_fact:
    provisioning_subnet: "{{ ip | ipaddr('network') }}/{{ ip | ipaddr('prefix') }}"
  vars:
    ip: "{{ ansible_facts[provisioning_bridge]['ipv6'][0]['address'] }}/{{ansible_facts[provisioning_bridge]['ipv6'][0]['prefix'] }}"
  when:
    - ipv6_enabled|bool
    - release_version[0]|int == 4 and release_version[2]|int > 3 or
      release_version[0]|int > 4
    - not ipv4_provisioning|bool
    - not enable_redfish_virtualmedia|bool
    - not enable_idrac_virtualmedia|bool
  tags:
  - network_facts

- debug:
    msg: "external subnet {{ extcidrnet }}"
    verbosity: 2
  tags:
  - network_facts

- debug:
    msg: "provisioning subnet {{ provisioning_subnet }}"
    verbosity: 2
  tags:
  - network_facts
