---
- include_tasks: 10_validation.yml
  tags: 
  - validation
  - create_registry
  
- include_tasks: 15_validation_disconnected_registry.yml
  when:
    - "'registry_host' in groups"
    - "groups['registry_host']"
  tags: 
  - disconnected
  - create_registry

- include_tasks: 20_sub_man_register.yml
  tags: subscription
- include_tasks: 30_req_packages.yml
  tags: packages
- include_tasks: 40_bridge.yml
  tags:
  - network
- include_tasks: 45_networking_facts.yml
  tags:
  - network_facts
- include_tasks: 50_modify_sudo_user.yml
  tags: user
- include_tasks: 60_enabled_services.yml
  tags: services
- include_tasks: 70_enabled_fw_services.yml
  tags: firewall
- include_tasks: 80_libvirt_pool.yml
  tags: storagepool
- include_tasks: 90_create_config_install_dirs.yml
  tags: clusterconfigs
- include_tasks: 100_power_off_cluster_servers.yml
  tags: powerservers
