- include_role:
    name: bootstrap
    tasks_from: 25_copykeys.yml
  vars:
    hostname: "{{ provisioner_hostname }}"
    ssh_user: "kni"

- include_role: 
    name: bootstrap
    tasks_from: 30_get_interpreter.yml
  vars:
    hostname: "{{ provisioner_hostname }}"
    user: "kni"

- name: python interpreter
  set_fact:
    python_interpreter: "{{ (python_version.stderr_lines|length > 0) | ternary('/usr/libexec/platform-python', '/usr/bin/python') }}"

- name: add provisioner to inventory file
  add_host:
    name: "{{ provisioner_hostname }}"
    groups: "provisioner"
    ansible_host: "{{ provisioner_hostname }}"
    ansible_ssh_private_key_file: "{{ ansible_ssh_key }}"
    ansible_user: "kni"
    ansible_python_interpreter: "{{ python_interpreter }}"

