apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  name: kubelet-worker-rt 
spec:
  machineConfigPoolSelector:
    matchLabels:
      worker-rt: ""
  kubeletConfig:
    systemReserved:
      cpu: 1000m
      memory: 500Mi
    kubeReserved:
      cpu: 1000m
      memory: 500Mi
    cpuManagerPolicy: static
    topologyManagerPolicy: best-effort

# options: https://github.com/kubernetes/kubernetes/blob/release-1.14/pkg/kubelet/apis/config/types.go#L62
