---

- name: Configure to use existing disconnected registry
  block:

    - name: Get stats of {{ disconnected_registry_mirrors_file }}
      stat:
        path: "{{ disconnected_registry_mirrors_file }}"
      register: drm_file

    - name: Check if the {{ disconnected_registry_mirrors_file }} exists
      fail:
        msg:
          - "The disconnected_registry_mirrors_file is defined, but does not exist"
      when: drm_file.stat.exists != true

    - name: Read the contents of {{ disconnected_registry_mirrors_file }}
      slurp:
        src: "{{ disconnected_registry_mirrors_file }}"
      register: disconnected_registry_trustbundle
      no_log: true

    - name: Set the install_config_appends fact
      set_fact:
        install_config_appends: "{{ disconnected_registry_trustbundle.content | string | b64decode }}"
      no_log: true

    - name: Get stats of {{ disconnected_registry_auths_file }}
      stat:
        path: "{{ disconnected_registry_auths_file }}"
      register: dra_file

    - name: Check if the {{ disconnected_registry_auths_file }} exists
      fail:
        msg:
          - "The disconnected_registry_auths_file is defined, but does not exist"
      when: dra_file.stat.exists != true

    - name: Read disconnected auths
      slurp:
        src: "{{ disconnected_registry_auths_file }}"
      register: disconnected_auths_b64
      no_log: true

    - name: append auth to pullsecret
      shell: |
        echo '{{ pullsecret }}' | jq -c \
          '.auths += {{ disconnected_auths_b64.content | string | b64decode }}'
      register: new_pullsecret
      no_log: true

    - name: set pullsecret with new auth
      set_fact:
        pullsecret: "  {{ new_pullsecret.stdout }}"
      no_log: true
  delegate_to: localhost
