---
- name: Get COMMIT_ID
  shell: |
    /usr/local/bin/openshift-baremetal-install version | grep '^built from commit' | awk '{print $4}' 
  register: commit_id

- name: Get RHCOS JSON File
  uri:
    url: https://raw.githubusercontent.com/openshift/installer/{{ commit_id.stdout }}/data/data/rhcos.json
    return_content: yes
  register: rhcos_json

- name: Set Facts for RHCOS_URI and RHCOS_PATH
  set_fact:
    rhcos_qemu_uri: "{{ rhcos_json.json | json_query('images.qemu.path') }}"
    rhcos_uri: "{{ rhcos_json.json | json_query('images.openstack.path') }}"
    rhcos_path: "{{ rhcos_json.json | json_query('baseURI') }}"
  
