---
- name: Check if override path is defined for extra openshift manifests
  set_fact:
    extramanifestsopenshift_path: "{{ customize_extramanifestsopenshift_path | default( 'roles/installer/files/openshift/*' ) }}"

- name: Add Manifests from files dir
  copy:
    src: "{{ item }}"
    dest: "{{ dir }}/openshift/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_fileglob:
    - "{{ extramanifestsopenshift_path }}"
  tags: extramanifests

- name: Check if override path is defined for extramanifests
  set_fact:
    extramanifests_path: "{{ customize_extramanifests_path | default( 'roles/installer/files/manifests/*' ) }}"

- name: Add Manifests from files dir
  copy:
    src: "{{ item }}"
    dest: "{{ dir }}/manifests/"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  with_fileglob:
    - "{{ extramanifests_path }}"
  tags: extramanifests

- name: Manage chrony configuration
  block:
  - name: Create chrony.conf
    set_fact:
      chronyconfig: "{{ lookup('template', 'chrony.conf.j2') | b64encode }}"

  - name: Inject chrony.conf in a machine-config object
    template:
      src: etc-chrony.conf.j2
      dest: "{{ dir }}/openshift/98-{{ item }}-etc-chrony.conf.yaml"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
    with_items:
      - master
      - worker
  when: (clock_servers is defined) and (clock_servers | length > 0)
  tags: extramanifests
