---
# defaults file for node-prep
activation_key: ""
org_id: ""
network_type: "OVNKubernetes"
firewall: "firewalld"
ipv6_enabled: false
no_proxy_list: ""
http_proxy: ""
https_proxy: ""
ipv4_baremetal: false
ipv4_provisioning: false
provisioning_bridge: "provisioning"
webserver_url: ""
baremetal_bridge: "baremetal"
disable_bmc_certificate_verification: false
redfish_inspection: true
enable_virtualmedia: false
