apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
    labels:
        machineconfiguration.openshift.io/role: worker-rt
    name: 11-rt-kernel-worker-rt
spec:
    config:
        ignition:
            config: {}
            security:
                tls: {}
            timeouts: {}
            version: 2.2.0
        networkd: {}
        passwd: {}
        storage:
            files:
                - filesystem: root
                  path: /usr/local/bin/rt-kernel-patch.sh
                  mode: 0700
                  contents:
                      source: data:text/plain;charset=utf-8;base64,IyEvYmluL2Jhc2gKCnNldCAtZXVvIHBpcGVmYWlsCgppZiBbWyAhIC1mIC9ldGMveXVtLnJlcG9zLmQvcmhlbC5yZXBvIF1dCnRoZW4KICAgICMgRW5hYmxlIHl1bSByZXBvCiAgICBta2RpciAtcCAvZXRjL3l1bS5yZXBvcy5kCiAgICBjYXQgPiAvZXRjL3l1bS5yZXBvcy5kL3JoZWwucmVwbyA8PEVPRgpbcnRdCmJhc2V1cmw9JHtSVF9SRVBPX1VSTH0KZ3BnY2hlY2s9MApFT0YKZmkKCiMgSW5zdGFsbCBwYXRjaGVkIG1pY3JvY29kZQojIHNlZSBodHRwczovL3NyYy5vc2NpLnJlZGhhdC5jb20vcnBtcy9taWNyb2NvZGVfY3RsL3B1bGwtcmVxdWVzdC85CnJlcGxhY2VkUGFja2FnZXM9JChycG0tb3N0cmVlIHN0YXR1cyAtLWpzb24gfCBqcSAnLmRlcGxveW1lbnRzW10gfCBzZWxlY3QoLmJvb3RlZCA9PSB0cnVlKSB8IC4ibGF5ZXJlZC1jb21taXQtbWV0YSIuInJwbW9zdHJlZS5yZXBsYWNlZC1iYXNlLXBhY2thZ2VzIicpCmlmIFtbICRyZXBsYWNlZFBhY2thZ2VzID1+ICJtaWNyb2NvZGVfY3RsIiBdXQp0aGVuCiAgICBlY2hvICJtaWNyb2NvZGVfY3RsIHBhdGNoIGFscmVhZHkgaW5zdGFsbGVkIgplbHNlCiAgICBycG0tb3N0cmVlIG92ZXJyaWRlIHJlcGxhY2UgJHtNSUNST0NPREVfVVJMfQpmaQoKIyBTd2FwIHRvIFJUIGtlcm5lbAprZXJuZWw9JCh1bmFtZSAtYSkKaWYgW1sgJGtlcm5lbCA9fiAiUFJFRU1QVCBSVCIgXV0KdGhlbgogICAgIyBUT0RPOiBjaGVjayBmb3IgUlQga2VybmVsIHVwZGF0ZXMKICAgIGVjaG8gIlJUIGtlcm5lbCBhbHJlYWR5IGluc3RhbGxlZCIKZWxzZQogICAgc3lzdGVtY3RsIHJlYm9vdApmaQo=
        systemd:
            units:
                - contents: |
                      [Unit]
                      Description=RT kernel patch
                      Wants=network-online.target
                      After=network-online.target
                      Before=kubelet.service

                      [Service]
                      Type=exec
                      RemainAfterExit=true

                      Environment=MICROCODE_URL=http://file.rdu.redhat.com/~walters/microcode_ctl-20190918-3.rhcos.1.el8.x86_64.rpm
                      Environment=RT_REPO_URL=http://download-node-02.eng.bos.redhat.com/rhel-8/nightly/RHEL-8/latest-RHEL-8.1.1/compose/RT/$basearch/os

                      ExecStart=/usr/local/bin/rt-kernel-patch.sh

                      [Install]
                      WantedBy=multi-user.target
                  enabled: true
                  name: rt-kernel.service