# Site settings
show_downloads: false
title: 'OpenShift Cluster Managed Bare Metal Documentation'
description: "Documents produced by Deployment Integration team"
permalink: pretty
repository: openshift-kni/baremetal-deploy
baseurl: https://openshift-kni.github.io/baremetal-deploy/


plugins: [jekyll-paginate, jekyll-asciidoc, jekyll-redirect-from, jekyll-feed, jekyll-sitemap, premonition, jekyll/tagging,  jekyll-seo-tag]

# Site settings
future: false

# Build settings
markdown: kramdown
type: website

exclude:
  - GUIDELINES.md
  - README.md
  - TODO.md
  - .history

tag_page_layout: tag
tag_page_dir: /tag/

kramdown:
  input: GFM
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
